#+TITLE: Doctoral course: longitudinal causal inference
#+Author: Thomas Alexander Gerds, University of Copenhagen
#+Date: 
#+EMAIL: tag@biostat.ku.dk
#+LaTeX_CLASS: org-article
#+OPTIONS: toc:nil
#+LaTeX_HEADER:\usepackage{authblk}
#+LaTeX_HEADER:\usepackage{natbib}
#+LaTeX_HEADER:\author{}
#+LaTeX_HEADER:\affil{Department of Biostatistics, University of Copenhagen}
#+SETUPFILE: ./practicals-html-export.setup
# #+setupfile:~/emacs-genome/snps/org-templates/setup-all-purpose.org
#+superman-org-export-target: html

The practicals will appear here.

* COMMENT Practical 1

** TODO 

Read the abstract of Robins & Finkelstein (2000). Biometrics 56,
pages 779--788. For your convenience the abstract is pasted in
here.

#+BEGIN_EXAMPLE
SUMMARY. AIDS Clinical Trial Group (ACTG) randomized trial 021 compared the effect of bactrim versus
aerosolized pentamidine (AP) as prophylaxis therapy for pneumocystis pneumonia (PCP) in AIDS patients.
Although patients randomized to the bactrim arm experienced a significant delay in time to PCP, the
survival experience in the two arms was not significantly different (p = .32). In this paper, we present
evidence that bactrim therapy improves survival but that the standard intent-to-treat comparison failed to
detect this survival advantage because a large fraction of the subjects either crossed over to the other therapy
or stopped therapy altogether. We obtain our evidence of a beneficial bactrim effect on survival by artificially
regarding the subjects as dependently censored at the first time the subject either stops or switches therapy;
we then analyze the data with the inverse probability of censoring weighted Kaplan-Meier and Cox partial
likelihood estimators of Robins (1993, Proceedings of the Biopharmaceutical Section, American Statistical
Association, pp. 24-33) that adjust for dependent censoring by utilizing data collected on time-dependent
prognostic factors.
#+END_EXAMPLE

** TODO 

Read from the middle of the first column of page 780 starting with
   "More precisely, ..." until "... their inverse probability of
   censoring weighted versions". For your convenience this part of the
   text is pasted in here.

#+BEGIN_EXAMPLE
More precisely, we will report four different causal analyses.

The first analysis is similar to a standard intent-to-treat anal-
ysis with mortality as the outcome; i.e., we compare mortal-
ity experience in the two treatment arms with death censored
only by loss to or end of follow-up. Thus, all 94 deaths are
regarded as failures. The novelty in the first analysis is that
we allow for the possibility of dependent censoring by loss to
follow-up.

In our second analysis, we compare mortality in the two
treatment arms while regarding a subject as dependently cen-
sored by the minimum of time to loss to follow-up and time to
treatment crossover. Thus, only the 73 of the 94 deaths that
occurred before a subject crossed over to the other arm are
included as failures; the other 21 deaths are regarded as cen-
sored. This analysis attempts to estimate what the survival
curves would have been if the possibility of crossover to the
other treatment arm after the development of PCP had been
eliminated from the treatment protocol.

In our third analysis, we compare the mortality in the two
treatment arms while regarding subjects as dependently cen-
sored at the minimum of time to loss to follow-up, time to
treatment crossover, and time to voluntarily stopping therapy
(for nonmedically related reasons). In this analysis, only the
52 of the 94 deaths in which subjects had neither crossed over
nor voluntarily stopped therapy are regarded as failures. For
public health purposes, this analysis may be preferred since
it attempts to estimate the survival benefit of bactrim com-
pared to aerosolized pentamidine had no subject voluntarily
stopped their assigned therapy without medical indication.

Our final analysis compares mortality in the two treatment
arms while regarding subjects as censored at the minimum of
time to loss to follow-up, crossover, or stopping therapy for
any reason. In this analysis, we are attempting to compare the
effect of bactrim versus aerosolized pentamidine on survival if
all subjects were forced to stay on their assigned therapy. Even
if we could successfully estimate this parameter, it would only
be of public health relevance if, as discussed above, the toxi-
cities that led to medically indicated termination of therapy
could be ameliorated with appropriate palliative therapy.

Since one would expect that the sickest patients would tend
to cross over or to stop therapy, it is clear that we must re-
gard censoring by crossover or stopping therapy as dependent.
However, Robins (1993) and Robins and Rotnitzky (1992)
showed that, if we have available data on all time-dependent
prognostic factors for mortality that independently predict
censoring, then one can correct for the dependence between
the censoring and failure by replacing the Kaplan-Meier es-
timator, log-rank test, and Cox partial likelihood estimator
of the ratio of the treatment-arm-specific mortality rates by
their inverse probability of censoring weighted versions.
#+END_EXAMPLE


** TODO 

The authors describe 4 different causal analyses which differ
regarding how and when the followup data are censored. Describe the
corresponding treatment regimens/protocols for one of the treatments
(bactrim or aerosolized pentamidine) of an emulated target
trial. Write your description in an R-markdown or quarto document.

| Analysis | Description in Finkelstein & Robins                                                                                  | Treatment protocol |
|----------+----------------------------------------------------------------------------------------------------------------------+--------------------|
| I        | A subject is censored only by loss to or end of follow-up                                                            |                    |
|----------+----------------------------------------------------------------------------------------------------------------------+--------------------|
| II       | Regard a subject as dependently censored by the minimum of time to loss to follow-up and time to treatment crossover |                    |
|----------+----------------------------------------------------------------------------------------------------------------------+--------------------|
| III      |                                                                                                                      |                    |
|----------+----------------------------------------------------------------------------------------------------------------------+--------------------|
| IV       |                                                                                                                      |                    |


* COMMENT Practical 2

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output raw  :exports code  :session *R* :cache yes  
library(rtmle)
#+END_SRC
